# Generated by Django 3.1.3 on 2022-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220927_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chocies',
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
